[2024-10-15T15:10:10.950+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_v07.extract manual__2024-10-15T15:00:07.514936+00:00 [queued]>
[2024-10-15T15:10:10.958+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_v07.extract manual__2024-10-15T15:00:07.514936+00:00 [queued]>
[2024-10-15T15:10:10.958+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 6
[2024-10-15T15:10:10.969+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract> on 2024-10-15 15:00:07.514936+00:00
[2024-10-15T15:10:10.974+0000] {standard_task_runner.py:57} INFO - Started process 1856 to run task
[2024-10-15T15:10:10.976+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_v07', 'extract', 'manual__2024-10-15T15:00:07.514936+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpudibm7vj']
[2024-10-15T15:10:10.979+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask extract
[2024-10-15T15:10:11.018+0000] {task_command.py:415} INFO - Running <TaskInstance: main_v07.extract manual__2024-10-15T15:00:07.514936+00:00 [running]> on host 86aea83cc069
[2024-10-15T15:10:11.081+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_v07' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T15:00:07.514936+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T15:00:07.514936+00:00'
[2024-10-15T15:10:11.083+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/extract/extract.py", line 4, in extract_data
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-15T15:10:11.091+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=main_v07, task_id=extract, execution_date=20241015T150007, start_date=20241015T151010, end_date=20241015T151011
[2024-10-15T15:10:11.100+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task extract (No module named 'pyspark'; 1856)
[2024-10-15T15:10:11.109+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-15T15:10:11.130+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
