[2024-10-15T14:40:17.138+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_v07.create_schema manual__2024-10-15T14:35:15.129691+00:00 [queued]>
[2024-10-15T14:40:17.146+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_v07.create_schema manual__2024-10-15T14:35:15.129691+00:00 [queued]>
[2024-10-15T14:40:17.147+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 6
[2024-10-15T14:40:17.157+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_schema> on 2024-10-15 14:35:15.129691+00:00
[2024-10-15T14:40:17.163+0000] {standard_task_runner.py:57} INFO - Started process 1110 to run task
[2024-10-15T14:40:17.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_v07', 'create_schema', 'manual__2024-10-15T14:35:15.129691+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpn929jbp2']
[2024-10-15T14:40:17.169+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask create_schema
[2024-10-15T14:40:17.213+0000] {task_command.py:415} INFO - Running <TaskInstance: main_v07.create_schema manual__2024-10-15T14:35:15.129691+00:00 [running]> on host 86aea83cc069
[2024-10-15T14:40:17.285+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_v07' AIRFLOW_CTX_TASK_ID='create_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T14:35:15.129691+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T14:35:15.129691+00:00'
[2024-10-15T14:40:17.286+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS staging_data (
        work_year INT,
        experience_level VARCHAR(50),
        employment_type VARCHAR(50),
        job_title VARCHAR(100),
        salary DECIMAL(10, 2),
        salary_currency VARCHAR(10),
        salary_in_usd DECIMAL(10, 2),
        employee_residence VARCHAR(100),
        remote_ratio INT CHECK (remote_ratio IN (0, 50, 100)),
        company_location VARCHAR(100),
        company_size CHAR(1) CHECK (company_size IN ('S', 'M', 'L')),
        load_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
[2024-10-15T14:40:17.293+0000] {base.py:73} INFO - Using connection ID 'postgresid' for task execution.
[2024-10-15T14:40:17.303+0000] {base.py:73} INFO - Using connection ID 'postgresid' for task execution.
[2024-10-15T14:40:25.327+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2024-10-15T14:40:25.343+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=main_v07, task_id=create_schema, execution_date=20241015T143515, start_date=20241015T144017, end_date=20241015T144025
[2024-10-15T14:40:25.362+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task create_schema (could not translate host name "host.docker.internal" to address: Name or service not known
; 1110)
[2024-10-15T14:40:25.403+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-15T14:40:25.438+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
