[2024-10-15T17:41:10.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T17:41:10.579+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_v09.add_constraints manual__2024-10-15T17:41:07.322116+00:00 [queued]>
[2024-10-15T17:41:10.588+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_v09.add_constraints manual__2024-10-15T17:41:07.322116+00:00 [queued]>
[2024-10-15T17:41:10.588+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-15T17:41:10.722+0000] {taskinstance.py:2888} INFO - Executing <Task(MySqlOperator): add_constraints> on 2024-10-15 17:41:07.322116+00:00
[2024-10-15T17:41:10.728+0000] {standard_task_runner.py:72} INFO - Started process 405 to run task
[2024-10-15T17:41:10.734+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_v09', 'add_constraints', 'manual__2024-10-15T17:41:07.322116+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpe7tqyhq6']
[2024-10-15T17:41:10.738+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask add_constraints
[2024-10-15T17:41:10.780+0000] {task_command.py:467} INFO - Running <TaskInstance: main_v09.add_constraints manual__2024-10-15T17:41:07.322116+00:00 [running]> on host d4bd6f97aac1
[2024-10-15T17:41:10.852+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_v09' AIRFLOW_CTX_TASK_ID='add_constraints' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T17:41:07.322116+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T17:41:07.322116+00:00'
[2024-10-15T17:41:10.852+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T17:41:10.864+0000] {sql.py:274} INFO - Executing: 
    USE main;
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_job FOREIGN KEY (job_id) REFERENCES job_dim(job_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_company FOREIGN KEY (company_id) REFERENCES company_dim(company_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_currency FOREIGN KEY (currency_id) REFERENCES currency_dim(currency_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_employee FOREIGN KEY (employee_id) REFERENCES employee_dim(employee_id);
    
[2024-10-15T17:41:10.874+0000] {base.py:84} INFO - Retrieving connection 'mariadb'
[2024-10-15T17:41:10.884+0000] {base.py:84} INFO - Retrieving connection 'mariadb'
[2024-10-15T17:41:10.896+0000] {sql.py:418} INFO - Running statement: 
    USE main;
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_job FOREIGN KEY (job_id) REFERENCES job_dim(job_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_company FOREIGN KEY (company_id) REFERENCES company_dim(company_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_currency FOREIGN KEY (currency_id) REFERENCES currency_dim(currency_id);
    
    ALTER TABLE jobs_fact
    ADD CONSTRAINT IF NOT EXISTS fk_employee FOREIGN KEY (employee_id) REFERENCES employee_dim(employee_id);
    , parameters: None
[2024-10-15T17:41:10.897+0000] {sql.py:427} INFO - Rows affected: 0
[2024-10-15T17:41:10.897+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 401, in run
    self.descriptions.append(cur.description)
  File "/usr/local/lib/python3.8/contextlib.py", line 299, in __exit__
    self.thing.close()
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 103, in close
    self._discard()
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FOREIGN KEY (job_id) REFERENCES job_dim(job_id);\n    \n    ALTER TABLE jobs_fa...' at line 2")
[2024-10-15T17:41:10.912+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_v09, task_id=add_constraints, run_id=manual__2024-10-15T17:41:07.322116+00:00, execution_date=20241015T174107, start_date=20241015T174110, end_date=20241015T174110
[2024-10-15T17:41:10.923+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T17:41:10.923+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task add_constraints ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FOREIGN KEY (job_id) REFERENCES job_dim(job_id);\n    \n    ALTER TABLE jobs_fa...' at line 2"); 405)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 401, in run
    self.descriptions.append(cur.description)
  File "/usr/local/lib/python3.8/contextlib.py", line 299, in __exit__
    self.thing.close()
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 103, in close
    self._discard()
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FOREIGN KEY (job_id) REFERENCES job_dim(job_id);\n    \n    ALTER TABLE jobs_fa...' at line 2")
[2024-10-15T17:41:10.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T17:41:10.958+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T17:41:10.960+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
