[2024-10-15T14:16:55.737+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_v07.create_schema scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-10-15T14:16:55.746+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_v07.create_schema scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-10-15T14:16:55.746+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2024-10-15T14:16:55.756+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_schema> on 2024-10-01 00:00:00+00:00
[2024-10-15T14:16:55.762+0000] {standard_task_runner.py:57} INFO - Started process 481 to run task
[2024-10-15T14:16:55.767+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_v07', 'create_schema', 'scheduled__2024-10-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp56l_uneg']
[2024-10-15T14:16:55.771+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask create_schema
[2024-10-15T14:16:55.829+0000] {task_command.py:415} INFO - Running <TaskInstance: main_v07.create_schema scheduled__2024-10-01T00:00:00+00:00 [running]> on host 86aea83cc069
[2024-10-15T14:16:55.905+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_v07' AIRFLOW_CTX_TASK_ID='create_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T00:00:00+00:00'
[2024-10-15T14:16:55.906+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS staging_data (
        work_year INT,
        experience_level VARCHAR(50),
        employment_type VARCHAR(50),
        job_title VARCHAR(100),
        salary DECIMAL(10, 2),
        salary_currency VARCHAR(10),
        salary_in_usd DECIMAL(10, 2),
        employee_residence VARCHAR(100),
        remote_ratio INT CHECK (remote_ratio IN (0, 50, 100)),
        company_location VARCHAR(100),
        company_size CHAR(1) CHECK (company_size IN ('S', 'M', 'L')),
        load_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
[2024-10-15T14:16:55.923+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgresqldata` isn't defined
[2024-10-15T14:16:55.927+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=main_v07, task_id=create_schema, execution_date=20241001T000000, start_date=20241015T141655, end_date=20241015T141655
[2024-10-15T14:16:55.936+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task create_schema (The conn_id `postgresqldata` isn't defined; 481)
[2024-10-15T14:16:55.977+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-15T14:16:56.026+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
